### ISSUE TITLE
possible error in gaussiansubpixel.cpp

### ISSUE THREAD

**Issue by rcojocaru** [OpenPIV/openpiv-c--qt#10]
Hi. 

I think that the final < should be a > in line 65:
if (!(i < (maxI+1) && i > (maxI-1) && j < (maxJ+1) && j < (maxJ-1)))
in gaussiansubpixel.cpp (https://github.com/OpenPIV/openpiv-c--qt/blob/master/src/gaussiansubpixel.cpp).

**Comment by timdewhirst** [comment]
closing as this code had been replaced.
