### ISSUE TITLE
Skipping Image Pairs on Import

### ISSUE THREAD

**Issue by rschurch** [OpenPIV/openpiv-c--qt#11]
I am trying to import images from a folder, and when creating the image pairs openpiv-c--qt skips pairs. For example, it will create a pair for image 1 and 2, and then 3 and 4, but NOT 2 an 3. If the folder contains many images, more images are skipped. For example, a pair between image 1 and 2 will be formed, and then again between 5 and 6.

**Comment by alexlib** [comment]
thanks for reaching out @rschurch - could you please help to get more info about your installation? What is the C++, Qt, platform? 

Thanks

**Comment by rschurch** [comment]
I am on a Dell XPS 15 with Ubuntu:
- gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0, 
- QMake version 2.01a; Using Qt version 4.8.7 in /usr/lib/x86_64-linux-gnu
Does that help?

**Comment by timdewhirst** [comment]
@rschurch : would it be possible to add an example directory listing please; this will help to reproduce the issue.

**Comment by rschurch** [comment]
@alexlib, I attach a zip file with the test images. With this folder I got pairs:
- image-001.jpg and image-002.jpg
- image-003.jpg and image-004.jpg

but not
- image-002 and image-003.jpg

And as mentioned, with bigger folders the gaps between pairs seem to increase.

[test2.zip](https://github.com/OpenPIV/openpiv-c--qt/files/3128592/test2.zip)

Thanks for your quick responses!

**Comment by alexlib** [comment]
> I am on a Dell XPS 15 with Ubuntu:
> 
> * gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0,
> * QMake version 2.01a; Using Qt version 4.8.7 in /usr/lib/x86_64-linux-gnu
>   Does that help?

I'll also try to install on a virtual Ubuntu and see if I can reproduce it. Do you have your installation instructions maybe?

**Comment by rschurch** [comment]
I just followed the instructions that are on your page (https://github.com/OpenPIV/openpiv-c--qt#installations-instructions-for-general-linux)

I take it, the import works on other systems then?

**Comment by timdewhirst** [comment]
@rschurch from scanning the code (see importimages.cpp, ImportImages::autoConfig() around L153) I can see two heuristics: look for images with an a/b identifier, or look for a numbered sequence. In the case of a numbered sequence then the pairs are assumed to be e.g. (001, 002), (003, 004), ... which is what you describe. 

There are then a few issues here: 
1) the heuristic may not be working correctly for larger folders
2) the heuristic isn't what you want in this case (you want (001, 002), (002, 003), (003, 004), ...)
3) there is no way to override the heuristic

I'll have a think about this; I think the code will need some work.

**Comment by rschurch** [comment]
OK, thanks. I was not aware of the a/b heuristic. Maybe the ffmpeg to create the image sequence can be run two times then, to produce the a/b pairs. I will give that a try.

**Comment by rschurch** [comment]
Creating the image sequences with two passes of ffmpeg worked like a charm, so if the a/b heuristic (and maybe some example ffmpeg commads) was reflected in the `getting_started.html` there would not be any need for fixes in the code.

**Comment by timdewhirst** [comment]
Good to hear that solved your issue; I've updated the documentation. If you're happy feel free to close! Thanks!

**Comment by alexlib** [comment]
@timdewhirst thanks for taking care
