### ISSUE TITLE
overlap with independent x and y size

### ISSUE THREAD

**Issue by ErichZimmer** [OpenPIV/openpiv-c--qt#18]
Define overlap in pixels [y, x] and calculate the overlap percentage for y and x axis in `core::generate_cartesian_grid` to create a flexible grid configurator. Not sure how many users would use it, but it is somewhat helpful in turbulent flows with not much movement in one of the axes.

**Comment by timdewhirst** [comment]
Yes, good point and trivial to do. In fact, this reminds me that I should generalize the correlation tests to cover non-square interrogation windows (which should be possible).
