### ISSUE TITLE
which image bit size to use

### ISSUE THREAD

**Issue by ErichZimmer** [OpenPIV/openpiv-c--qt#19]
When converting Numpy arrays to usable arrays for openPIV-c++, which bit size should we use for best performance to precision ratio? Would 16 bit arrays be the best middle ground for preprocessed images?

PS, what is core::g_f data type? I been searching around for ~30 minutes and couldn't find a definitive answer.

**Comment by timdewhirst** [comment]
Second question first: g_f is defined in pixel_types.h:

```
openpiv/core/pixel_types.h:280:using g_f  = g<double>;
```

i.e. this is a greyscale pixel with underlying type of double. At the moment the pixel types are rgba, yuva, complex and greyscale, and all of these are templated for the underlying type e.g. rgba_8 is an RGBA pixel (that is: red, green, blue and alpha values) where each value is an unsigned 8-bit integer.

core::image is a class template taking a pixel type as its template parameter; this means that the core currently supports packed image formats internally only, not planar (see https://en.wikipedia.org/wiki/Packed_pixel)

numpy: good question! I imagined, when considering adding a python wrapper for openpiv, that the heavy lifting would be done within c++, with only algorithm strategy and output in python. Why would we use numpy to load image data to then pass to the c++ side? I'm assuming the intended use case is e.g. pre-processing of image data before performing correlation?

**Comment by ErichZimmer** [comment]
My idea was to wrap the `pyprocess` module in c++ since it is a bottleneck for large images (high ram usage, relatively slow correlation performance). The plan was something like this.
```python
def fft_correlate_images(
    numpy.ndarray: img_a, # passed as pointer to c++ side
    numpy.ndarray: img_b, # passed as pointer to c++ side
    tuple(int, int): window_size, 
    tuple(int, int): overlap
) -> numpy.ndarray # 3 dimensional correlation matrix

def correlation_to_displacements(
    numpy.ndarray: cmatrix, # passed as pointer to c++ side
    int: n_rows,
    int: n_cols,
    string: subpixel_method # not used
) -> numpy.ndarray, numpy.ndarray, numpy.ndarray # u, v, s2n
```
These functions would call the raw c++ wrapper and make sure everything is checked before passing the data to the c++ side. On some tests (wrapped the `preprocess` module to see if it's possible), the wrapped functions were more than three times faster than pure numpy or scipy functions and scaled linearly.

Just for clarification, I am returning the correlation matrix so that some users could performance multi-frame or ensemble correlation.

**Comment by timdewhirst** [comment]
okay, this looks like a highly relevant page:

https://pybind11.readthedocs.io/en/stable/advanced/pycpp/numpy.html

**Comment by ErichZimmer** [comment]
My first few attempts:
https://github.com/ErichZimmer/pybind11_MWEs/tree/main/test0

**Comment by ErichZimmer** [comment]
Since the preprocessed images are almost always grayscale floating point arrays, does it make sense to rescale the image and static_cast it to a usable pixel type or should we rescale the image and pass it as a pointer to fill an interrogation window before cross correlation?

Theoretical processing chain for former:
- Convert and rescale float image to uint8 or uint16
- pass numpy array to c++ side
- convert numpy array to usable data structure
- proceed as normal

Theoretical processing chain for latter:
- Convert and rescale float image to uint8 or uint16
- pass numpy array to c++ side
- pass pointer to a c++ function (use static_cast on pointer?)
- fill interrogation windows from pointer (similar to legacy version of OpenPIV-c++)
- proceed as normal

**Comment by timdewhirst** [comment]
In general, if we're aiming for speed/computational efficiency, we should avoid conversion as much as possible. I think the majoriy of native image formats are unsigned integer of various bit depth, so I would suggest that if as part of the load we convert from integer to real (float, double) for pre-processing, we should maintain that format all the way through. I think this is possible using the python buffer protocol, and because openpiv-c++'s core classes are templated then adding a new underlying pixel type should be trivial. 

We currently support greyscale images with unsigned int of 8, 16, 32 bits and also double.

Do you have an example of an image load/preprocessing step in python that I could use to check this when passing to the C++ side?

**Comment by ErichZimmer** [comment]
Here is a quick example.
https://github.com/ErichZimmer/pybind11_MWEs/blob/main/test0/test.ipynb
The images were not converted back to original data type because OpenPIV-Python FFTs convert all input arrays to 32 bit floats.

**Comment by ErichZimmer** [comment]
I find that converting numpy arrays to different data types on the python side is quite efficient most of the time. Using this, converting 32 bit floats to something more usable or faster would not have a significant impact on performance.

**Comment by ErichZimmer** [comment]
Does OpenPIV::core support c-style arrays?

**Comment by timdewhirst** [comment]
The quick answer is: yes. 

The fuller answer is: openpiv::core::image is the core class for image data, and this assumes ownership of the image data; this is signified by the use (currently) of a std::vector as the data type (see openpiv::core::image::data_t). The nice thing about std::vector is that memory management is done for you, and the data is guaranteed to be contiguous. This allows c-array like use and behaviour e.g. openpiv::core::image::data() returns a pointer to the container pixel type, and in fact this method of operating on the image data is the most commonly used.

If we want to change the ownership model e.g. to allow operation on a buffer passed from python, it's absolutely possible.

**Comment by ErichZimmer** [comment]
I found an efficiency issue in my code.
I couldn't get std:: reference_wrapper to work, so I looped through the pointers to fill an image. It is not terrible slow, but it was the only solution I got working without compiler errors.

**Comment by timdewhirst** [comment]
Excellent - can you push your code to a branch or raise a PR so that I can take a look?
