### ISSUE TITLE
Warning: No resources in 'share/images/images.qrc'

### ISSUE THREAD

**Issue by gabyx** [OpenPIV/openpiv-c--qt#3]
When I run qmake-qt4   in the source directory of the current git clone
I get this error?

Warning: No resources in 'share/images/images.qrc'

**Comment by lcabon258** [comment]
I have the same problem as above.
I'm using Qt5.6 on windows. In "Qt5.6 for desktop (MinGW 4.9.2 32bit)" window, I give the command and it responses like below :  
===== ===== =====
```
E:\piv\openpiv-c--qt-master> qmake "openpiv-c++.pro"
RCC: Warning: No resources in 'share\images\images.qrc'.
RCC: Warning: No resources in 'share\images\images.qrc'.
```
===== ===== =====
Is there any solution so far ? Thanks !

**Comment by zjtaylor** [comment]
We have not done any testing in Qt5 of the C++ branch of OpenPIV. I would suggest using Qt4 if you want to try and use our quite alpha version of OpenPIV in C++. 

Regarding the error, I believe it is simply a warning and should not prevent compilation or running of the program.

**Comment by timdewhirst** [comment]
closing as this code had been replaced.
