### ISSUE TITLE
What image types are supported 

### ISSUE THREAD

**Issue by ErichZimmer** [OpenPIV/openpiv-c--qt#31]
I know RGB and grey scale images are supported, but what about the extension types of images (e.g. bmp, tiff, jpg, jpeg...)?

**Comment by timdewhirst** [comment]
At the moment we support PNM and TIFF; the idea was to avoid external library dependencies and leave image conversion to other existing libraries e.g. libpnm. There are some special image formats that I think it would make sense to support e.g. RAW and output from specialist cameras like PCO (.b16).

Adding new image format support is reasonably straightforward - a new subclass of image_loader should be created.

**Comment by ErichZimmer** [comment]
Okay, it all makes sense now.
