### ISSUE TITLE
when  I run the process.exe, use the picture in examples, but the output is very different from "README" file. and the result have the same piv.xy.

### ISSUE THREAD

**Issue by 992308385** [OpenPIV/openpiv-c--qt#32]
After I  cmake the openpiv, I run the process.exe, use the picture in examples, but the output is very different from "README" file. and the ### piv.xy are all the  same in different rows,.  when I debug, i find the "grid" is right,the result.xy is not the same as "grid" point, and all the result.xy almost the same,  i have run the project in two computers and get the same result.  my os is windows 10.  
the result of piv1.pgm and piv2.pgm,  
![image](https://user-images.githubusercontent.com/17736667/199379286-e4869267-5965-4688-b769-4044688c0c28.png)

the result of exp1_001_a.tiff and exp1_001_b.tiff,
![image](https://user-images.githubusercontent.com/17736667/199381662-b539faf4-0469-4e9d-b613-97d4f902b47b.png)

**Comment by timdewhirst** [comment]
Thanks for the report; investigating...

**Comment by timdewhirst** [comment]
Should be fixed now; thanks again for reporting!
