### ISSUE TITLE
does not compile with qt4 on ubuntu! -> FIX provided

### ISSUE THREAD

**Issue by gabyx** [OpenPIV/openpiv-c--qt#4]
Hello with installed qt4 it does not compile it seems you are mixing QtGUi and QtWidgets (qt5) includes:

with the following regex replacements the stuff compiles finally! (execute in source folder!) -> 

see pull request

**Comment by zjtaylor** [comment]
Note that this is still very much a development version of OpenPIV, so bugs are not at all surprising.

Can you please be more specific with regards to the error you are receiving when trying to compile using Qt 4? The code was written for Qt 4 and should compile as-is. Please summarize the error that you received upon trying to compile and the steps used to reproduce the error.

**Comment by timdewhirst** [comment]
closing as this code had been replaced.
