### ISSUE TITLE
Windows VS2017 build Error

### ISSUE THREAD

**Issue by VegetaZhang** [OpenPIV/openpiv-c--qt#41]
Thank you for your selfless dedication. There are some compilation error issues that need to be consulted. My environment is Windows 10 and I use vs 2017 to build the code.
I first built the vs2017 solution using 'cmake-B build-S'. Then I reported the following error while build openpivcore.  I tried to correct the errors, but I could not fix them. If you have time, would you please provide some solutions? Thank you.
![image](https://user-images.githubusercontent.com/34471274/235287305-60c4e806-d554-4834-b9d9-e628e1cf22c8.png)

**Comment by VegetaZhang** [comment]
​Here is the configuration of my project, ​We look forward to your reply, thank you.
![image](https://user-images.githubusercontent.com/34471274/235287456-39df08bb-f539-48f2-b312-e1421aa8bfac.png)

**Comment by alexlib** [comment]
@timdewhirst @ErichZimmer - do you have some experience with this error?

**Comment by timdewhirst** [comment]
Hello, and thanks for the report.

I suspect the issue is due to the old version of Visual Studio - it could be that not all C++17 features were correctly supported. I'll see if it's possible to reproduce using github's actions, but failing that, is it possible to upgrade to a newer version of Visual Studio?

**Comment by VegetaZhang** [comment]
Thank you for your advice. I will try to build with a new version of VS. If there is any progress, I will let everyone know again.

**Comment by VegetaZhang** [comment]
Good news, after switching to vs2022, it has been successfully built. Thank you again for your help.

**Comment by timdewhirst** [comment]
great to hear, thanks for the update!
