### ISSUE TITLE
Compiling but not working

### ISSUE THREAD

**Issue by supvato** [OpenPIV/openpiv-c--qt#9]
Hello and thanks for developing an open PIV software. 

I've apparently been succesful in compiling (an openpiv-c++ application is created and opens), however, it does not appear to be functional. As instructed, I first run qmake (ver. 2.01a using Qt ver. 4.8.6), which generates an empty _build directory and a Makefile. I then run make and get a few warnings but no errors (see output file attached). This fills the  _build directory with files and creates the openpiv-c++ application. 

The application opens, but most of the push buttons, e.g. 'Help', 'Tutorials' and 'About' in the Help tab, are unresponsive. 

I am able to open the import dialog and choose a folder to import, but the 'imported' images appear completely black and the correlation button produces a file full of NaNs (see attachment).

 What do you think is the problem? Have you guys seen something like this before? Thanks for any help.

P.S.: I am using Linux Mint 17 (Qiana) and have recently installed and upgraded libtiff4 and fftw3. 

[A001_1.txt](https://github.com/OpenPIV/openpiv-c--qt/files/367553/A001_1.txt)

[out.txt](https://github.com/OpenPIV/openpiv-c--qt/files/367551/out.txt)

**Comment by timdewhirst** [comment]
Hello!

Thanks for getting in touch. The first thing to say is that this 
codebase is in the process of being refactored and is very short of 
volunteers so effectively should be considered incomplete.

Having said that, thanks for the report that the code is building and 
starting.

I'll take a look at the code and remind myself of the current state.

Thanks!

**Comment by timdewhirst** [comment]
closing as this code had been replaced.
